name: mangastash_extension
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1


dependencies:
  dart_eval: ^0.8.2
  eval_annotation: ^0.8.1

  manga_dex_api:
    git:
      url: https://github.com/robzimpulse/mangastash
      ref: decouple-external-source
      path: module/library/manga_dex_api
  entity_manga_external:
    git:
      url: https://github.com/robzimpulse/mangastash
      ref: decouple-external-source
      path: module/library/entity_manga_external

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
